export const TEXT = {
  member: {
    title: "정산할 사람들의 이름을 입력해주세요!",
    alert_duplicate: "중복된 이름입니다.",
    button: "명 정산 시작",
    button_add: "추가",
    button_delete: "삭제",
    placeholder: "이름 입력 후 엔터",
  },
  money: {
    title: "결제한 내역들을 입력해주세요!",
    button: "정산 결과 보기",
    button_add: "추가하기",
    button_delete: "삭제",
    back: "처음부터 다시 시작하기",
    label1: "결제한 사람",
    label2: "엔빵할 사람들",
    label3: "결제한 금액",
  },
  paymentItem: {
    allSelected: "전체",
    emptySelected: "(엔빵 대상자들을 선택해주세요)",
    moneyUnit: "원",
    placeholderMemo: "내용을 입력해주세요(선택)",
  },
  result: {
    title: "엔빵 완료!",
    back: "결제 내역 수정하기",
    label1: "보내는 사람",
    label2: "받는 사람",
    label3: "보낼 돈",
    label4: "이름",
    label5: "결제한 돈",
    label6: "사용한 돈",
    label7: "받을/보낼돈",
  },
};
